openapi: 3.0.0
info:
  title: User Feedback API
  version: 1.0.0
  description: API documentation for the User Feedback application
paths:
  /api/feedback:
    post:
      summary: Create a new feedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback:
                  type: string
                product_id:
                  type: integer
                user_id:
                  type: integer
      responses:
        '201':
          description: Feedback created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
        '500':
          description: Internal server error
    get:
      summary: Get all feedback
      responses:
        '200':
          description: A list of feedback
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'
        '500':
          description: Internal server error
  /api/feedback/{id}:
    get:
      summary: Get feedback by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Feedback found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
    put:
      summary: Update feedback by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback:
                  type: string
                product_id:
                  type: integer
                user_id:
                  type: integer
      responses:
        '200':
          description: Feedback updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
        '403':
          description: Not allowed to update user
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
    delete:
      summary: Delete feedback by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Feedback deleted successfully
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
components:
  schemas:
    Feedback:
      type: object
      properties:
        id:
          type: integer
        feedback:
          type: string
        product_id:
          type: integer
        user_id:
          type: integer